// This file is part of the Prowl Game Engine
// Licensed under the MIT License. See the LICENSE file in the project root for details.

using Prowl.Echo;

namespace Prowl.Runtime.Resources;

/// <summary>Where a prefab's contents come from, which decides whether they can be written back.</summary>
public enum PrefabInstanceType
{
    /// <summary>An authored .prefab asset. Editable, and instances can apply their overrides to it.</summary>
    Prefab,

    /// <summary>
    /// Generated by importing a source file, such as a model. Read-only: its contents are rebuilt on
    /// every import, so anything written to it would be discarded, and writing to the file it came
    /// from would destroy that file. Instances still track and revert overrides.
    /// </summary>
    Model
}

/// <summary>
/// A prefab asset: a serialized GameObject hierarchy, stored as raw EchoObject data.
/// <para/>
/// Instantiating one lives on <see cref="GameObject"/> - see
/// <see cref="GameObject.Instantiate(PrefabAsset)"/> to spawn into a scene, or
/// <see cref="GameObject.InstantiateDetached"/> for the hierarchy on its own - so that every way of
/// building a GameObject from serialized data goes through one place.
/// </summary>
public class PrefabAsset : EngineObject
{
    [SerializeField]
    private EchoObject? _gameObjectData;

    [SerializeField]
    private PrefabInstanceType _instanceType = PrefabInstanceType.Prefab;

    /// <summary>Where this prefab's contents come from. Set by whatever produces the asset.</summary>
    public PrefabInstanceType InstanceType
    {
        get { EnsureNotDisposed(); return _instanceType; }
        set { EnsureNotDisposed(); _instanceType = value; }
    }

    /// <summary>
    /// True when this prefab is generated rather than authored, so nothing may be written back to it.
    /// </summary>
    public bool IsReadOnly => InstanceType != PrefabInstanceType.Prefab;

    /// <summary>
    /// The serialized GameObject hierarchy in Echo format. Assigning takes a copy: every instantiation
    /// reads this tree, so a caller that kept a handle to what it assigned could otherwise change what
    /// future instances come out as.
    /// </summary>
    public EchoObject? GameObjectData
    {
        get { EnsureNotDisposed(); return _gameObjectData; }
        set { EnsureNotDisposed(); _gameObjectData = value?.Clone(); }
    }
}
