// This file is part of the Prowl Game Engine
// Licensed under the MIT License. See the LICENSE file in the project root for details.

using System;
using System.Collections.Generic;

using Prowl.Echo;

namespace Prowl.Runtime.Resources;

/// <summary>Where a prefab's contents come from, which decides whether they can be written back.</summary>
public enum PrefabInstanceType
{
    /// <summary>An authored .prefab asset. Editable, and instances can apply their overrides to it.</summary>
    Prefab,

    /// <summary>
    /// Generated by importing a source file, such as a model. Read-only: its contents are rebuilt on
    /// every import, so anything written to it would be discarded, and writing to the file it came
    /// from would destroy that file. Instances still track and revert overrides.
    /// </summary>
    Model
}

/// <summary>
/// A prefab asset: a serialized GameObject hierarchy, stored as raw EchoObject data. Holding a prefab keeps every
/// asset its hierarchy uses loaded, so spawning it never loads.
/// <para/>
/// Instantiating one lives on <see cref="GameObject"/> - see
/// <see cref="GameObject.Instantiate(PrefabAsset)"/> to spawn into a scene, or
/// <see cref="GameObject.InstantiateDetached"/> for the hierarchy on its own - so that every way of
/// building a GameObject from serialized data goes through one place.
/// </summary>
public class PrefabAsset : Asset, IAssetWalkable
{
    [SerializeField]
    private EchoObject? _gameObjectData;

    [NonSerialized] private Asset[]? _referencedAssets;

    [SerializeField]
    private PrefabInstanceType _instanceType = PrefabInstanceType.Prefab;

    /// <summary>Where this prefab's contents come from. Set by whatever produces the asset.</summary>
    public PrefabInstanceType InstanceType
    {
        get { EnsureLoaded(); return _instanceType; }
        set { EnsureLoaded(); _instanceType = value; }
    }

    /// <summary>
    /// True when this prefab is generated rather than authored, so nothing may be written back to it.
    /// </summary>
    public bool IsReadOnly => InstanceType != PrefabInstanceType.Prefab;

    /// <summary>
    /// The serialized GameObject hierarchy in Echo format. Assigning takes a copy: every instantiation
    /// reads this tree, so a caller that kept a handle to what it assigned could otherwise change what
    /// future instances come out as.
    /// </summary>
    public EchoObject? GameObjectData
    {
        get { EnsureLoaded(); return _gameObjectData; }
        set
        {
            EnsureLoaded();
            _gameObjectData = value?.Clone();
            _referencedAssets = null;
        }
    }

    /// <summary>Every asset the stored hierarchy names, loaded or not.</summary>
    public IReadOnlyList<Asset> ReferencedAssets
    {
        get
        {
            EnsureLoaded();
            return _referencedAssets ??= StoredTree.ReferencedAssets(_gameObjectData);
        }
    }

    void IAssetWalkable.Walk(AssetWalker walker)
    {
        foreach (Asset asset in ReferencedAssets)
            walker.Visit(asset);
    }
}

/// <summary>Reads the asset references out of a stored hierarchy without building it.</summary>
public static class StoredTree
{
    /// <summary>The stable object for every <c>$asset</c> stub in the tree, loaded or not.</summary>
    public static Asset[] ReferencedAssets(EchoObject? tree)
    {
        var found = new List<Asset>();
        var seen = new HashSet<Guid>();
        Collect(tree, found, seen);
        return found.ToArray();
    }

    private static void Collect(EchoObject? tag, List<Asset> found, HashSet<Guid> seen)
    {
        if (tag == null) return;
        if (tag.TagType == EchoType.List)
        {
            foreach (EchoObject item in tag.List) Collect(item, found, seen);
            return;
        }
        if (tag.TagType != EchoType.Compound) return;

        if (tag.TryGet(AssetReferenceRule.AssetKey, out EchoObject? stub) && Guid.TryParse(stub!.StringValue, out Guid id)
            && seen.Add(id) && AssetDatabase.Get(id) is { } asset)
            found.Add(asset);

        foreach (EchoObject child in tag.Tags.Values) Collect(child, found, seen);
    }
}
