// This file is part of the Prowl Game Engine
// Licensed under the MIT License. See the LICENSE file in the project root for details.

using System;
using System.Linq;

using Prowl.Echo;

namespace Prowl.Runtime.Resources;

/// <summary>Where a prefab's contents come from, which decides whether they can be written back.</summary>
public enum PrefabInstanceType
{
    /// <summary>An authored .prefab asset. Editable, and instances can apply their overrides to it.</summary>
    Prefab,

    /// <summary>
    /// Generated by importing a source file, such as a model. Read-only: its contents are rebuilt on
    /// every import, so anything written to it would be discarded, and writing to the file it came
    /// from would destroy that file. Instances still track and revert overrides.
    /// </summary>
    Model
}

/// <summary>
/// A prefab asset containing a serialized GameObject hierarchy.
/// The GO tree is stored as raw EchoObject data and instantiated on demand.
/// </summary>
public class PrefabAsset : EngineObject
{
    [SerializeField]
    private EchoObject? _gameObjectData;

    [SerializeField]
    private PrefabInstanceType _instanceType = PrefabInstanceType.Prefab;

    /// <summary>Where this prefab's contents come from. Set by whatever produces the asset.</summary>
    public PrefabInstanceType InstanceType
    {
        get { EnsureNotDisposed(); return _instanceType; }
        set { EnsureNotDisposed(); _instanceType = value; }
    }

    /// <summary>
    /// True when this prefab is generated rather than authored, so nothing may be written back to it.
    /// </summary>
    public bool IsReadOnly => InstanceType != PrefabInstanceType.Prefab;

    /// <summary>
    /// The serialized GameObject hierarchy in Echo format. Assigning takes a copy: every instantiation
    /// reads this tree, so a caller that kept a handle to what it assigned could otherwise change what
    /// future instances come out as.
    /// </summary>
    public EchoObject? GameObjectData
    {
        get { EnsureNotDisposed(); return _gameObjectData; }
        set { EnsureNotDisposed(); _gameObjectData = value?.Clone(); }
    }

    /// <summary>
    /// Instantiate a live GameObject from this prefab.
    /// The returned GO has PrefabAssetId set to this asset's GUID.
    /// Add it to a scene to make it active.
    /// </summary>
    /// <returns>The new hierarchy, or null if this asset has no data or it could not be read.</returns>
    public GameObject? Instantiate()
    {
        EnsureNotDisposed();

        if (_gameObjectData == null)
        {
            Debug.LogWarning($"[Prefab] '{Name}' has no GameObject data to instantiate.");
            return null;
        }

        GameObject? clone;
        try
        {
            // A prefab cannot reference objects outside itself, so anything the editor recorded as an
            // external reference instantiates as null rather than as an empty object built from the stub.
            clone = Serializer.Deserialize<GameObject>(_gameObjectData,
                new SerializationContext { ExternalReferences = SceneReferenceResolver.None });
        }
        catch (Exception ex)
        {
            Debug.LogError($"[Prefab] Failed to instantiate '{Name}': {ex.Message}");
            return null;
        }

        if (clone == null)
        {
            Debug.LogError($"[Prefab] '{Name}' did not deserialize into a GameObject.");
            return null;
        }

        StampPrefabId(clone, AssetID);
        return clone;
    }

    /// <summary>
    /// Stamps PrefabAssetId on a GO and its children.
    /// Skips children that already have a different PrefabAssetId (nested prefab instances).
    /// </summary>
    private static void StampPrefabId(GameObject go, Guid prefabAssetId)
    {
        go.PrefabAssetId = prefabAssetId;

        // Only the editor reads these, and they are what the structural rules in the hierarchy and
        // inspector are enforced from. A player pays a walk per spawn for state nothing consults.
        if (Application.IsEditor)
        {
            go.PrefabComponentCount = go._components.Count;
            go.PrefabChildCount = go.Children.Count;
        }

        foreach (var child in go.Children)
        {
            // Don't overwrite nested prefab instances
            if (child.IsPrefabInstance && child.PrefabAssetId != prefabAssetId)
                continue;
            StampPrefabId(child, prefabAssetId);
        }
    }
}
